spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: security
    password: security
  security:
    user:
      password: password
  sql:
    init:
      mode: always
#logging:
#  level:
#    org.springframework.security: trace